# Generated by Django 5.1.3 on 2024-11-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_banners/'),
        ),
    ]
