# Generated by Django 5.1.3 on 2024-11-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at_sri_lanka',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
