# Generated by Django 5.1.3 on 2024-11-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_created_at_sri_lanka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at_sri_lanka',
        ),
    ]
