# Generated by Django 5.1.3 on 2024-11-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_tag_post_categories_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
